# https://readthedocs.org/projects/mpi4py/builds/

version: 2

sphinx:
   configuration: docs/source/usrman/conf.py
   fail_on_warning: true

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
   install:
     - path: .
     - requirements: conf/requirements-docs.txt
