target-version = "py38"

src = ["src"]

exclude = [
"demo",
"test",
]

lint.select = [
"A",
"B",
"C",
"D",
"E",
"F",
"G",
"I",
"Q",
"S",
"W",
"UP",
"ARG",
"ISC",
"PIE",
#"PTH",
"PYI",
"RET",
"RUF",
"TRY",
"YTT",
]

lint.ignore = [
"A001",
"A002",
"A003",
"A005",
"C901",
"I001",
"Q000",
"PYI011",
"UP006",
"UP007",
"RET504",
"RET505",
"RUF012",
"RUF022",
"TRY003",
]

[lint.per-file-ignores]
"conf/*" = ["D",]
"demo/*" = ["D",]
"docs/*" = ["D",]
"test/*" = ["D",]
"*.pyi"  = ["D", "E501"]

[lint.pydocstyle]
convention = "pep257"
