version: 2.1
orbs:
  codecov: codecov/codecov@3.2.3

jobs:
  test:
    parameters:
      os:
        type: executor
      py:
        type: string
      mpi:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run: .circleci/test-package py=<< parameters.py >> mpi=<< parameters.mpi >>
      - codecov/upload

executors:
  linux:
    docker:
      - image: condaforge/linux-anvil-cos7-x86_64

workflows:
  test-all:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
                - maint
                - ci/all
                - ci/circle
          matrix:
            parameters:
              os:
                - linux
              py:
                - "3.6"
                - "3.7"
                - "3.8"
                - "3.9"
                - "3.10"
                - "3.11"
              mpi:
                - "mpich"
                - "openmpi"
